### ISSUE TITLE
CAM for action recognition?

### ISSUE THREAD

**Issue by kentwhf** [fitushar/3D-Grad-CAM#1]
Hello,

I took a quick look into the code and found your data in "nii.gz" format, but I assume it is still taken as images (height, width, channels) by the model right? I don't have much knowledge regarding biomedical imaging tho..

Could this script be used for video analysis? I fed my 3D CNN with video data, which has the dimension of time.

**Comment by fitushar** [comment]
Hi, the Input dimension of the Nifti data ( nii.gz) is (Height ,weight ,depth, Channel). I never worked with Video Data but if your Data is having this dimension in theory it should work.

**Comment by kentwhf** [comment]
Thanks. I got the desired graphs.
